export const metadata = {
  title: "Product page",
  description: "Generated by create next app",
};

export default function Product() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      Product Page
    </main>
  );
}
